name: Deploy The Code Kitchen to Azure Container Apps

on:
  workflow_dispatch:

jobs:
  build-orleans-silo:
    name: Build Orleans Silo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Login to ACR
        run: |
          az acr login --name crthecodekitchen
    
      - name: Build Orleans Silo Docker image
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t crthecodekitchen.azurecr.io/ca-tck-orleans-silo:latest \
                       -t crthecodekitchen.azurecr.io/ca-tck-orleans-silo:$IMAGE_TAG \
                       -f TheCodeKitchen/TheCodeKitchen.Infrastructure.Orleans.Silo/Dockerfile TheCodeKitchen/

      - name: Push Orleans Silo Docker Image to ACR
        run: |
          docker push crthecodekitchen.azurecr.io/ca-tck-orleans-silo --all-tags

  build-orleans-scaler:
    name: Build Orleans Scaler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Login to ACR
        run: |
          az acr login --name crthecodekitchen
    
      - name: Build Orleans Scaler Docker image
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t crthecodekitchen.azurecr.io/ca-tck-orleans-scaler:latest \
                       -t crthecodekitchen.azurecr.io/ca-tck-orleans-scaler:$IMAGE_TAG \
                       -f TheCodeKitchen/TheCodeKitchen.Infrastructure.Orleans.Scaler/Dockerfile TheCodeKitchen/

      - name: Push Orleans Scaler Docker Image to ACR
        run: |
          docker push crthecodekitchen.azurecr.io/ca-tck-orleans-scaler --all-tags


  build-cook-api:
    name: Build Cook API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Login to ACR
        run: |
          az acr login --name crthecodekitchen
          
      - name: Build Cook API Docker image
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t crthecodekitchen.azurecr.io/ca-tck-cook-api:latest \
                       -t crthecodekitchen.azurecr.io/ca-tck-cook-api:$IMAGE_TAG \
                       -f TheCodeKitchen/TheCodeKitchen.Presentation.CookAPI/Dockerfile TheCodeKitchen/

      - name: Push Cook API Docker Image to ACR
        run: |
          docker push crthecodekitchen.azurecr.io/ca-tck-cook-api --all-tags

  build-management-api:
    name: Build Management API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Login to ACR
        run: |
          az acr login --name crthecodekitchen
    
      - name: Build Management API Docker image
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t crthecodekitchen.azurecr.io/ca-tck-management-api:latest \
                       -t crthecodekitchen.azurecr.io/ca-tck-management-api:$IMAGE_TAG \
                       -f TheCodeKitchen/TheCodeKitchen.Presentation.ManagementAPI/Dockerfile TheCodeKitchen/

      - name: Push Management API Docker Image to ACR
        run: |
          docker push crthecodekitchen.azurecr.io/ca-tck-management-api --all-tags

  build-management-ui:
    name: Build Management UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Login to ACR
        run: |
          az acr login --name crthecodekitchen
    
      - name: Build Management UI Docker image
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t crthecodekitchen.azurecr.io/ca-tck-management-ui:latest \
                       -t crthecodekitchen.azurecr.io/ca-tck-management-ui:$IMAGE_TAG \
                       -f TheCodeKitchen/TheCodeKitchen.Presentation.ManagementUI/Dockerfile TheCodeKitchen/

      - name: Push Management UI Docker Image to ACR
        run: |
          docker push crthecodekitchen.azurecr.io/ca-tck-management-ui --all-tags

  deploy-orleans-silo:
    name: Deploy Orleans Silo
    needs: build-orleans-silo
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Orleans Silo to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: crthecodekitchen.azurecr.io/ca-tck-orleans-silo:${{ github.run_number }}
          registryUrl: crthecodekitchen.azurecr.io
          containerAppName: ca-tck-orleans-silo
          resourceGroup: rg-the-code-kitchen
          containerAppEnvironment: cae-the-code-kitchen

  deploy-orleans-scaler:
    name: Deploy Orleans Scaler
    needs: [build-orleans-scaler, deploy-orleans-silo]
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Deploy Orleans Scaler to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: crthecodekitchen.azurecr.io/ca-tck-orleans-scaler:${{ github.run_number }}
          registryUrl: crthecodekitchen.azurecr.io
          containerAppName: ca-tck-orleans-scaler
          resourceGroup: rg-the-code-kitchen
          containerAppEnvironment: cae-the-code-kitchen

  deploy-cook-api:
    name: Deploy Cook API
    needs: [build-cook-api, deploy-orleans-silo]
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Cook API to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: crthecodekitchen.azurecr.io/ca-tck-cook-api:${{ github.run_number }}
          registryUrl: crthecodekitchen.azurecr.io
          containerAppName: ca-tck-cook-api
          resourceGroup: rg-the-code-kitchen
          containerAppEnvironment: cae-the-code-kitchen

  deploy-management-api:
    name: Deploy Management API
    needs: [build-management-api, deploy-orleans-silo]
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Management API to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: crthecodekitchen.azurecr.io/ca-tck-management-api:${{ github.run_number }}
          registryUrl: crthecodekitchen.azurecr.io
          containerAppName: ca-tck-management-api
          resourceGroup: rg-the-code-kitchen
          containerAppEnvironment: cae-the-code-kitchen

  deploy-management-ui:
    name: Deploy Management UI
    needs: [build-management-ui, deploy-orleans-silo]
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Management UI to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: crthecodekitchen.azurecr.io/ca-tck-management-ui:${{ github.run_number }}
          registryUrl: crthecodekitchen.azurecr.io
          containerAppName: ca-tck-management-ui
          resourceGroup: rg-the-code-kitchen
          containerAppEnvironment: cae-the-code-kitchen